# APPVEYOR CONFIGURATION FILE #

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

image: Visual Studio 2019

install:
  - ps: nuget restore

after_build:
  - ps: 7z a rajio.zip $Env:APPVEYOR_BUILD_FOLDER\Rajio\bin\Debug\*.*
  - ps: Push-AppveyorArtifact rajio.zip
